# tomcat_deploy.yml
---
- hosts: localhost
  tasks:
    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Deploy sample.war
      copy:
        src: sample.war
        dest: /var/lib/tomcat9/webapps/

    - name: Configure Tomcat heap size
      lineinfile:
        path: /etc/default/tomcat9
        regexp: '^(export CATALINA_OPTS=)'
        line: 'export CATALINA_OPTS="$CATALINA_OPTS -Xmx{{ heap_size }}"'
      vars:
        heap_size: "{{ '256m' if env == 'DEV' else '512m' }}"

    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
